[E 201202 01:47:40 Crawler:56] HTTPConnectionPool(host='102.64.120.87', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=152 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7621072bb0>, 'Connection to 102.64.120.87 timed out. (connect timeout=10)'))
[I 201202 01:47:40 Crawler:57] Try with a different proxy
[E 201202 01:47:56 Crawler:56] HTTPConnectionPool(host='77.83.87.155', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620872190>, 'Connection to 77.83.87.155 timed out. (connect timeout=10)'))
[I 201202 01:47:56 Crawler:57] Try with a different proxy
[E 201202 01:47:56 Crawler:56] HTTPConnectionPool(host='117.212.92.55', port=35636): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7621072730>: Failed to establish a new connection: [Errno 111] Connection refused')))
[I 201202 01:47:56 Crawler:57] Try with a different proxy
[E 201202 01:48:10 Crawler:56] HTTPConnectionPool(host='103.143.46.27', port=80): Read timed out. (read timeout=10)
[I 201202 01:48:10 Crawler:57] Try with a different proxy
[E 201202 01:48:20 Crawler:56] HTTPConnectionPool(host='202.142.153.181', port=38865): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620705fd0>, 'Connection to 202.142.153.181 timed out. (connect timeout=10)'))
[I 201202 01:48:20 Crawler:57] Try with a different proxy
[E 201202 01:48:31 Crawler:56] HTTPConnectionPool(host='192.168.0.125', port=808): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7621072040>, 'Connection to 192.168.0.125 timed out. (connect timeout=10)'))
[I 201202 01:48:31 Crawler:57] Try with a different proxy
[E 201202 01:48:41 Crawler:56] HTTPConnectionPool(host='193.56.72.136', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f762032edc0>, 'Connection to 193.56.72.136 timed out. (connect timeout=10)'))
[I 201202 01:48:41 Crawler:57] Try with a different proxy
[E 201202 01:48:51 Crawler:56] HTTPConnectionPool(host='118.174.233.45', port=44061): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f762032e610>, 'Connection to 118.174.233.45 timed out. (connect timeout=10)'))
[I 201202 01:48:51 Crawler:57] Try with a different proxy
[E 201202 01:49:01 Crawler:56] HTTPConnectionPool(host='80.82.55.71', port=8080): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f76208721f0>, 'Connection to 80.82.55.71 timed out. (connect timeout=10)'))
[I 201202 01:49:01 Crawler:57] Try with a different proxy
[E 201202 01:49:06 Crawler:56] HTTPConnectionPool(host='190.103.85.36', port=8080): Max retries exceeded with url: http://www.indeed.com/jobs?l=Houston%2C+TX&q=+data+engineer&start=0 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
[I 201202 01:49:06 Crawler:57] Try with a different proxy
[E 201202 01:49:22 Crawler:56] HTTPConnectionPool(host='31.129.253.30', port=40223): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f76210494f0>, 'Connection to 31.129.253.30 timed out. (connect timeout=10)'))
[I 201202 01:49:22 Crawler:57] Try with a different proxy
[E 201202 01:49:36 Crawler:56] HTTPConnectionPool(host='85.208.209.241', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f762036c7c0>, 'Connection to 85.208.209.241 timed out. (connect timeout=10)'))
[I 201202 01:49:36 Crawler:57] Try with a different proxy
[E 201202 01:49:47 Crawler:56] HTTPConnectionPool(host='103.250.166.4', port=6666): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f762036ca60>, 'Connection to 103.250.166.4 timed out. (connect timeout=10)'))
[I 201202 01:49:47 Crawler:57] Try with a different proxy
[E 201202 01:49:57 Crawler:56] HTTPConnectionPool(host='109.94.172.200', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f762036c0d0>, 'Connection to 109.94.172.200 timed out. (connect timeout=10)'))
[I 201202 01:49:57 Crawler:57] Try with a different proxy
[E 201202 01:50:20 Crawler:56] HTTPConnectionPool(host='102.64.120.39', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=45 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620f20340>, 'Connection to 102.64.120.39 timed out. (connect timeout=10)'))
[I 201202 01:50:20 Crawler:57] Try with a different proxy
[E 201202 01:50:30 Crawler:56] HTTPConnectionPool(host='213.166.76.230', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=45 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620f20eb0>, 'Connection to 213.166.76.230 timed out. (connect timeout=10)'))
[I 201202 01:50:30 Crawler:57] Try with a different proxy
[E 201202 01:50:40 Crawler:56] HTTPConnectionPool(host='102.64.122.127', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=45 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620f18310>, 'Connection to 102.64.122.127 timed out. (connect timeout=10)'))
[I 201202 01:50:40 Crawler:57] Try with a different proxy
[E 201202 01:50:41 Crawler:56] HTTPConnectionPool(host='193.36.61.203', port=8000): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=45 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7620f18e50>: Failed to establish a new connection: [Errno 111] Connection refused')))
[I 201202 01:50:41 Crawler:57] Try with a different proxy
[E 201202 01:50:51 Crawler:56] HTTPConnectionPool(host='119.8.44.244', port=8080): Read timed out. (read timeout=10)
[I 201202 01:50:51 Crawler:57] Try with a different proxy
[E 201202 01:51:01 Crawler:56] HTTPConnectionPool(host='102.64.120.100', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=45 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620f06400>, 'Connection to 102.64.120.100 timed out. (connect timeout=10)'))
[I 201202 01:51:01 Crawler:57] Try with a different proxy
[E 201202 01:51:01 Crawler:67] Stop scraping url http://www.indeed.com/jobs? after 5 failed attempts
[E 201202 01:51:05 Crawler:56] Exceeded 30 redirects.
[I 201202 01:51:05 Crawler:57] Try with a different proxy
[E 201202 01:51:15 Crawler:56] HTTPConnectionPool(host='102.64.122.127', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=60 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620cb5d90>, 'Connection to 102.64.122.127 timed out. (connect timeout=10)'))
[I 201202 01:51:15 Crawler:57] Try with a different proxy
[E 201202 01:51:25 Crawler:56] HTTPConnectionPool(host='189.194.48.26', port=8080): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=60 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620699910>, 'Connection to 189.194.48.26 timed out. (connect timeout=10)'))
[I 201202 01:51:25 Crawler:57] Try with a different proxy
[E 201202 01:51:35 Crawler:56] HTTPConnectionPool(host='85.208.211.41', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=60 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620cdc820>, 'Connection to 85.208.211.41 timed out. (connect timeout=10)'))
[I 201202 01:51:35 Crawler:57] Try with a different proxy
[E 201202 01:51:49 Crawler:56] HTTPConnectionPool(host='103.115.14.43', port=80): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620cdc1f0>, 'Connection to 103.115.14.43 timed out. (connect timeout=10)'))
[I 201202 01:51:49 Crawler:57] Try with a different proxy
[E 201202 01:52:03 Crawler:56] HTTPConnectionPool(host='213.166.79.138', port=8085): Max retries exceeded with url: http://www.indeed.com/jobs?l=Dallas%2C+TX&q=data+scientist&start=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7620cdcc70>, 'Connection to 213.166.79.138 timed out. (connect timeout=10)'))
[I 201202 01:52:03 Crawler:57] Try with a different proxy
