[E 201130 03:33:09 Crawler:56] HTTPConnectionPool(host='170.238.11.9', port=999): Max retries exceeded with url: http://www.indeed.com/jobs?q=data+scientist&l=Houston%2C+TX (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f22c10f4430>, 'Connection to 170.238.11.9 timed out. (connect timeout=10)'))
[I 201130 03:33:10 Crawler:57] Try with a different proxy
[E 201130 03:33:20 Crawler:56] HTTPConnectionPool(host='5.9.139.148', port=8080): Max retries exceeded with url: http://www.indeed.com/jobs?q=data+scientist&l=Houston%2C+TX (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f22c10f4cd0>, 'Connection to 5.9.139.148 timed out. (connect timeout=10)'))
[I 201130 03:33:20 Crawler:57] Try with a different proxy
[E 201130 03:35:08 Crawler:56] HTTPConnectionPool(host='51.75.147.40', port=3128): Read timed out. (read timeout=10)
[I 201130 03:35:08 Crawler:57] Try with a different proxy
